# .github/workflows/build-liquibase-image.yml
name: Build Liquibase image

on:
  push:
    branches:
      -  master
      -  develop
    paths:
      - 'db/**' 
      - '.github/docker/liquibase_custom.Dockerfile' 
      - '.github/workflows/build-liquibase-image.yml' 
  workflow_dispatch: 
    inputs:
      trigger_liquibase: 
        description: 'Set to "liquibase" to force a build (e.g., to rebuild image without code changes)'
        required: false
        default: '' 

env:
  IMAGE_NAME: ghcr.io/${{ github.repository_owner }}/liquibase

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions: 
      packages: write 
      contents: read  
    if: ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.trigger_liquibase == 'liquibase' || github.event_name == 'push' && github.event.before == '0000000000000000000000000000000000000000' || github.event_name == 'push' && github.event.before != '0000000000000000000000000000000000000000' }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }} 
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build + push image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: .github/docker/liquibase_custom.Dockerfile
          push: true
          tags: |
            ${{ env.IMAGE_NAME }}:${{ github.ref_name }}
    #        ${{ github.ref_name == 'master' && format('{0}:latest', env.IMAGE_NAME) || '' }}