name: Build Custom Postgres Image for MarketSim

on:
  push:
    paths:
      - '.github/docker/Postgres_Marketsim.Dockerfile'
      - '.github/docker/init.sql'
  workflow_dispatch:

env:
  IMAGE_NAME: ghcr.io/${{ github.repository_owner }}/postgres_marketsim
  IMAGE_TAG: v13.4-init

jobs:
  build-postgres-image:
    runs-on: ubuntu-latest

    permissions:
      packages: write
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and Push Postgres Image
        uses: docker/build-push-action@v5
        with:
          context: .github/docker
          file: .github/docker/Postgres_Marketsim.Dockerfile
          push: true
          tags: |
            ${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}