# .github/workflows/build-builder-image.yml
name: Build Builder Image

on:
  push:
    branches:
      - master
      - develop
    paths:
      - '.github/docker/Build_Marketsim.Dockerfile'
  workflow_dispatch:
    inputs:
      reason:
        description: 'Reason for manual builder image build (e.g., security updates)'
        required: false
        default: 'Manual trigger'

env:
  IMAGE_NAME: ghcr.io/${{ github.repository_owner }}/build_marketsim
  IMAGE_TAG: v0.1

jobs:
  build-builder-image:
    runs-on: ubuntu-latest

    permissions:
      packages: write
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push builder image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: .github/docker/Build_Marketsim.Dockerfile
          push: true
          tags: |
            ${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}