# .github/workflows/marketsim-ci.yml
name: Market Simulator CI

on:
  pull_request:
    branches:
      - master
      - develop
    types: [opened, synchronize, reopened]
  push:
    branches:
      - master
      - develop
    tags:
      - 'v[0-9]+.[0-9]+'
      - 'v[0-9]+'
  workflow_dispatch:

env:
 # BUILDER_IMAGE: ghcr.io/${{ github.repository_owner }}/build_marketsim:v0.1
  DEPLOY_IMAGE_BASE: ghcr.io/${{ github.repository }}/deploy_marketsim

jobs:
  release-with-deb-info-build:
    runs-on: ubuntu-latest
    if: ${{ (startsWith(github.ref, 'refs/tags/v') && github.ref_type == 'tag') || github.event_name == 'push' || github.event_name == 'pull_request' }}
    container:
      image: ghcr.io/${{ github.repository_owner }}/build_marketsim:v0.1
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Mark repository as safe
        run: git config --global --add safe.directory $GITHUB_WORKSPACE

      - name: Derive SIM_VERSION (major branch name or tag major)
        run: |
          if [[ "${GITHUB_REF}" == refs/tags/v* ]]; then
            MAJOR_VERSION=$(echo "${GITHUB_REF_NAME}" | sed -E 's/^v?([0-9]+).*/\1/')
            echo "Detected tag version: $MAJOR_VERSION"
          else
            MAJOR_VERSION="${GITHUB_REF_NAME}"
            echo "Using branch name as version: $MAJOR_VERSION"
          fi
          echo "SIM_VERSION=$MAJOR_VERSION" >> "$GITHUB_ENV"

      - name: Configure CMake
        run: cmake --preset ci-gitlab-release-with-debug-info-config -DSIM_VERSION=$SIM_VERSION

      - name: Build Project
        run: cmake --build --preset ci-gitlab-release-with-debug-info --target all 2>&1 | tee compilation_log.txt

      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-artifacts-${{ github.run_id }}
          path: |
            release-with-debug-info-build/
            compilation_log.txt
          retention-days: 2

  release-with-deb-info-test:
    runs-on: ubuntu-latest
    needs: release-with-deb-info-build
    if: ${{ (startsWith(github.ref, 'refs/tags/v') && github.ref_type == 'tag') || github.event_name == 'push' || github.event_name == 'pull_request' }}
    container:
      image: ghcr.io/${{ github.repository_owner }}/build_marketsim:v0.1
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download Build Artifacts
        uses: actions/download-artifact@v4
        with:
          name: build-artifacts-${{ github.run_id }}
          path: .

      - name: Make test binaries executable
        run: chmod +x release-with-debug-info-build/bin/* || true

      - name: Run CTest
        run: ctest --preset ci-gitlab-release-with-debug-info-test --output-junit test_report.xml

      - name: Upload Test Report
        uses: actions/upload-artifact@v4
        with:
          name: test-report-${{ github.run_id }}
          path: test_report.xml
          retention-days: 2

  create-marketsim-package:
    runs-on: ubuntu-latest
    needs: release-with-deb-info-test
    if: ${{ (startsWith(github.ref, 'refs/tags/v') && github.ref_type == 'tag') || github.event_name == 'push' || github.event_name == 'pull_request' }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download Build Artifacts
        uses: actions/download-artifact@v4
        with:
          name: build-artifacts-${{ github.run_id }}
          path: .

      - name: Create Marketsimulator Package
        run: |
          echo "Creating marketsimulator package"
          mkdir -p package/quod/bin
          mkdir -p package/quod/script
          cp -r release-with-debug-info-build/bin/marketsimulator package/quod/bin/
          cp -r cfg package/quod/
          cp -r db package/quod/
          cp -r script/launch_liquibase.sh package/quod/script/
          ls -la package/quod

      - name: Upload Package Artifact
        uses: actions/upload-artifact@v4
        with:
          name: marketsim-package-${{ github.run_id }}
          path: package/quod
          retention-days: 30

  create-marketsim-docker-for-deploy:
    runs-on: ubuntu-latest
    needs: create-marketsim-package
    if: ${{ (startsWith(github.ref, 'refs/tags/v') && github.ref_type == 'tag') || github.event_name == 'push' || github.event_name == 'pull_request' }}
    
    permissions:
      packages: write
      contents: read
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download Package Artifact
        uses: actions/download-artifact@v4
        with:
          name: marketsim-package-${{ github.run_id }}
          path: package/quod

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Determine Docker Image Tag
        env:
          SAFE_PR_BRANCH: ${{ github.head_ref }}
        run: |
          if [[ "${GITHUB_EVENT_NAME}" == "pull_request" ]]; then
            SAFE_TAG="$SAFE_PR_BRANCH"
          else
            SAFE_TAG="${GITHUB_REF_NAME}"
          fi

          BASE_TAG="ghcr.io/${GITHUB_REPOSITORY}/deploy_marketsim:$SAFE_TAG"
          echo "DEPLOY_IMAGE_FULL_TAG=$BASE_TAG" >> "$GITHUB_ENV"

          if [[ "$SAFE_TAG" == "master" && "${GITHUB_EVENT_NAME}" == "push" && "${GITHUB_REF}" != refs/tags/* ]]; then
            echo "DEPLOY_IMAGE_FULL_TAG=ghcr.io/${GITHUB_REPOSITORY}/deploy_marketsim:latest,$BASE_TAG" >> "$GITHUB_ENV"
          fi

      - name: Build and Push Deploy Image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: .github/docker/Deploy_Marketsim.Dockerfile
          push: true
          tags: ${{ env.DEPLOY_IMAGE_FULL_TAG }}
